### PR TITLE
Remove linking to erl_interface

### LINKED ISSUE #40: hdr_histogram_erl failed to compile with OTP23
I installed OTP 23.0 and found hdr_histogram_erl failed to compile (as a dependency of my application) with error 
`ld: library not found for -lerl_interface` 
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`.
 I have no background in C integration with Erlang but I guess this is due to the modification on `erl_interface` in OTP23.

I think you guys might have noticed this or it is already a work in progress, but I would like to post here anyway in case someone encountered similar problem.

Thanks.

### PR DESCRIPTION
**Pull request by petrohi**
Fixes #40

### CODE REVIEW

**Review by bryannaegele — APPROVED** [review]
Works for me! LGTM

**Comment by tsloughter** [comment]
I'm guessing it doesn't matter that this is only needed for 23+ since erl interface isn't used in the project?

Preferably just move to the `pc` plugin so it handles this stuff.

**Comment by petrohi** [comment]
So what's the plan/ETA to fix hdr_histogram_erl under OTP 23?

**Comment by tsloughter** [comment]
Hey, sorry abut that, I'm merging this.

**Pull request merged**
