### PR TITLE
Coalesce EQC test

### PR DESCRIPTION
**Pull request by jlouis**
This improves the EQC tests quite a bit by coalescing some things, so you can get away with doing one rather than more than one.

Rather than run two separate EQC tests, use one and make it do both
things at the same time. This allows us to test both variants of things
with one EQC test.

### CODE REVIEW

**Comment by darach** [comment]
LGTM. Hailing @Licenser to check and bless as I don't have EQC.

**Comment by jlouis** [comment]
Interestingly, it was enough to find a mistake...

**Comment by Licenser** [comment]
I would rather not merge it as it is. The test fails (which is OK, damn bugs!) but in the test fails with a wrong error (now that is a funny word). The error looks looks the `from_binary` function fails while from what I can tell already the `to_binary` function fails.

returning `{exception, Class, Err, Bin, H}` it reads like this `{exception,error,badarg,{error,bad_hdr_binary},<<>>}` which means to me that to_binary already failed (for an so far unknown reason).

To be fair it is putting the PR to a higher standard then the original code, but what can I say, I'm not a nice person ;). - no jokes aside while we're at it and see this we can as well improve right?

**Comment by Licenser** [comment]
Something along the lines of this:

``` diff
diff --git a/test/hdr_bin_tests_eqc.erl b/test/hdr_bin_tests_eqc.erl
index ac984d9..5abdb47 100644
--- a/test/hdr_bin_tests_eqc.erl
+++ b/test/hdr_bin_tests_eqc.erl
@@ -65,17 +65,20 @@ prop_to_bin() ->
                           nc -> ?H:to_binary(H);
                           {c, Opts} -> ?H:to_binary(H, Opts)
                       end,
-                Res = try ?H:from_binary(Bin) of
-                          {error, Reason} -> {error, Reason};
-                          {ok, H1} ->
-                              V1 = vals(H1),
-                              ?H:close(H1),
-                              V1
-                catch
-                    Class:Err ->
-                        {exception, Class, Err}
-                end,
-
+                Res = case Bin of
+                          _ when is_binary(Bin) ->
+                              try ?H:from_binary(Bin) of
+                                  {error, Reason} -> {error, Reason};
+                                  {ok, H1} ->
+                                      V1 = vals(H1),
+                                      ?H:close(H1),
+                                      V1
+                              catch
+                                  Class:Err ->
+                                      {exception, Class, Err}
+                              end;
+                          E -> E
+                      end,
                 V = vals(H),
                 ?H:close(H),
                 equals(V, Res)
```

**Comment by jlouis** [comment]
Ah, nice! I'll pull that suggestion in. It's good.

**Comment by tsloughter** [comment]
@jlouis @Licenser was this updated? Can I merge it now?

**Comment by Licenser** [comment]
go for it!

**Pull request merged**
