### PR TITLE
Add support for compilation through rebar3

### PR DESCRIPTION
**Pull request by jlouis**
Add the necessary pre/post hooks for rebar3 into the rebar.config file.
Then provide a makefile which outputs the same .so as the rebar 2 variant.

This passes all 18 Common Test cases if run through `rebar3 ct` as expected. I have not run the EQC test suite. Otherwise, things seems to work as expected.

### CODE REVIEW

**Comment by darach** [comment]
LGTM. Please add yourself to the AUTHORS file so I can merge. :)
You must be telepathic as @tsantero was just thinking rebar3 thoughts!

**Comment by tsloughter** [comment]
Note that edown and fqc are both on hex, so you could use packages.

Also, a dep like edown should go in the docs profile so everyone who depends on the app doesn't have to fetch and build edown :)

**Comment by darach** [comment]
@tsloughter Noted! :)

**Comment by jlouis** [comment]
This is now done, I'm in the `AUTHORS` list.

**Pull request merged**
